general.import = [
	"~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }

decorations = "None"

opacity = 0.8

[font]
normal = { family = "JetBrains Mono" }
size = 11
